### ISSUE TITLE
Bridge应用当共享的不是文件时，提示报错

### ISSUE THREAD

**Issue by Ricky-Hao** [RikkaApps/RikkaApps.github.io.backup#7]
使用**Bridge**的初衷是为了在**储存重定向**的情景下，共享**Share微博**的微博到**QQ**。  
但是，当在**Share微博**的共享中，选择**Bridge**的`转发`时，提示`这个应用没有发送文件`。  
个人认为可能是**Share微博**在共享到**QQ**时会生成文件，但是共享到其他应用时，生成的是文本化的`URL`链接。  
不知道**Bridge**能否对`文本共享`进行兼容？

**Comment by RikkaW** [comment]
停一停，Bridge 的初衷是分享文件到不支持接收 content uri 的应用（
既然都是文本了为什么要过 Bridge

**Comment by Ricky-Hao** [comment]
因为在**Share微博**里直接共享到**QQ**好像不是文本。。跟B站类似的

**Comment by RikkaW** [comment]
Bridge 只会处理 action 是 `ACTION_SEND` 或是 `ACTION_SEND_MULTIPLE` 并且带有 extra `EXTRA_STREAM`  的 intent，其他都会直接“这个应用没有发送文件”（
坏坏 Share微博 是什么情况就不知道了（

**Comment by Ricky-Hao** [comment]
那想知道，**QQ**和**哔哩哔哩**都放在储存重定向里，要怎么样才能从B站分享视频到QQ？（非`URL`形式

**Comment by ShmilyChen** [comment]
> 那想知道，**QQ**和**哔哩哔哩**都放在储存重定向里，要怎么样才能从B站分享视频到QQ？（非`URL`形式

折中的方法
在qq的来自共享空间的文件夹里面加上`Android/data/tv.danmaku.bili/`
同理Share也可以这样

**Comment by Ricky-Hao** [comment]
可以的，之前一直尝试**来自其他应用的隔离储存空间的文件夹**，但是就是不行- -可能是我太菜了吧
